language: go
go:
  - "1.12"

services:
  - docker

env:
  - GO111MODULE=on GOTIFY_VERSIONS="v2.0.5"

before_install:
  - make download-tools
  - go get -d

script:
  - go test ./...

before_deploy:
  - >
    for TARGET in $GOTIFY_VERSIONS; do
      make GOTIFY_VERSION="$TARGET" FILE_SUFFIX="-for-gotify-$TARGET" build;
    done
